DROP SCHEMA IF EXISTS  users_note;
CREATE SCHEMA users_note;
SET SCHEMA users_note;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  login VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE (`login`));

CREATE TABLE note (
  id INT NOT NULL AUTO_INCREMENT,
  id_user INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  note_body VARCHAR(1000) NOT NULL,
  date TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE metka (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE (`title`));

CREATE TABLE metka_note (
  id_note INT NOT NULL,
  id_metka INT NOT NULL);